name: Java Compile Check

on:
  push:
    branches: [ main ]
    paths:
      - 'exemplos/**/*.java'
  pull_request:
    branches: [ main ]
    paths:
      - 'exemplos/**/*.java'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile Examples
      run: |
        find ./exemplos -name "*.java" -type f | while read -r file; do
          echo "Compiling $file"
          javac "$file" || exit 1
        done
