name: Java Compile Check

on:
  push:
    branches: [ main ]
    paths:
      - 'exemplos/**/*.java'
  pull_request:
    branches: [ main ]
    paths:
      - 'exemplos/**/*.java'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Compile Examples
      run: |
        # Encontrar todos os diretórios com arquivos Java
        JAVA_DIRS=$(find ./exemplos -name "*.java" -type f -printf "%h\n" | sort | uniq)
        
        # Para cada diretório, compilar todos os arquivos Java juntos
        for dir in $JAVA_DIRS; do
          echo "Compilando arquivos em $dir"
          find "$dir" -name "*.java" -type f -print | xargs javac
        done
